### ISSUE TITLE
Phira crashes after a few days sideloaded

### ISSUE THREAD

**Issue by viyellaf0rsaken** [F-Unction/prpr_ipa#2]
I just sideloaded Phira on iPad Air 1, it a bit laggy when playing but still ok on overall. But after a few days, it always crashed on launch every single time and I have to uninstall and sideload again. Any solution?

**Comment by F-Unction** [comment]
"Sorry, I am not the author of Phira. If you have found any bugs in the game, please go to the original repository (https://github.com/TeamFlos/phira) to create an issue. Additionally, regarding the crashing issue you encountered, it might be caused by the invalid iOS software signature. You can consider using sideloading tools that are more convenient for resigning, such as AltStore."
